name: EduLearn Automation Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Install Chrome and Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable firefox
        # Set display for headless mode
        export DISPLAY=:99
        sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        
    - name: Create necessary directories
      run: |
        mkdir -p target/screenshots
        mkdir -p target/extent-reports
        mkdir -p target/logs
        mkdir -p downloads
        
    - name: Build with Maven
      run: mvn -B clean compile
      
    - name: Run Tests with System Properties
      run: |
        mvn -B test \
          -Dbrowser=${{ matrix.browser }} \
          -Dheadless=true \
          -Dbase.url=https://edulearn-demo.example.com \
          -Dmaven.test.failure.ignore=true \
          -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml
      continue-on-error: true
      
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        fail_on_failure: false
        
    - name: Archive Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports-${{ matrix.browser }}-${{ github.run_number }}
        path: |
          target/extent-reports/
          target/screenshots/
          target/logs/
          target/surefire-reports/
        retention-days: 30
        
    - name: Test Summary
      if: always()
      run: |
        echo "Test execution completed for ${{ matrix.browser }}"
        if [ -d "target/surefire-reports" ]; then
          echo "Surefire reports generated:"
          ls -la target/surefire-reports/
        fi
        if [ -d "target/extent-reports" ]; then
          echo "Extent reports generated:"
          ls -la target/extent-reports/
        fi
