name: EduLearn Automation Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Install browsers and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable firefox xvfb
        # Set display for headless mode
        export DISPLAY=:99
        sudo Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 3
        
    - name: Create necessary directories
      run: |
        mkdir -p target/screenshots
        mkdir -p target/extent-reports
        mkdir -p target/logs
        mkdir -p downloads
        
    - name: Verify Maven installation
      run: mvn --version
      
    - name: Build with Maven
      run: mvn -B clean compile
      
    - name: Run Tests with System Properties
      run: |
        mvn -B test \
          -Dbrowser=${{ matrix.browser }} \
          -Dheadless=true \
          -Dbase.url=https://www.google.com \
          -Dmaven.test.failure.ignore=true \
          -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml
      continue-on-error: true
      env:
        DISPLAY: :99
      
    - name: Verify test artifacts exist
      run: |
        echo "Checking for test artifacts..."
        find target -type f -name "*.xml" -o -name "*.html" -o -name "*.png" | head -10
        echo "Directory contents:"
        ls -la target/ 2>/dev/null || echo "Target directory does not exist"
        ls -la target/surefire-reports/ 2>/dev/null || echo "Surefire reports directory does not exist"
      
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        fail_on_failure: false
        
    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ matrix.browser }}-${{ github.run_number }}
        path: |
          target/extent-reports/
          target/screenshots/
          target/logs/
          target/surefire-reports/
        retention-days: 30
        if-no-files-found: warn
        
    - name: Test Summary
      if: always()
      run: |
        echo "============================================="
        echo "Test execution completed for ${{ matrix.browser }}"
        echo "============================================="
        
        if [ -d "target/surefire-reports" ]; then
          echo "✅ Surefire reports generated:"
          ls -la target/surefire-reports/
          echo ""
        else
          echo "❌ No surefire reports found"
        fi
        
        if [ -d "target/extent-reports" ]; then
          echo "✅ Extent reports generated:"
          ls -la target/extent-reports/
          echo ""
        else
          echo "❌ No extent reports found"
        fi
        
        if [ -d "target/screenshots" ]; then
          echo "📸 Screenshots captured:"
          ls -la target/screenshots/ | wc -l
          echo ""
        else
          echo "❌ No screenshots found"
        fi
        
        echo "============================================="